import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import ContactRibbon from "../components/ContactRibbon";
import { Navbar } from "../components/Navbar";
import OfferCards from "../components/OfferCards";
import Postnavbar from "../components/Postnavbar";
import Prenavbar from "../components/Prenavbar";
import RelevantInfoBanner from "../components/RelevantInfoBanner";
import Tabs from "../components/Tabs";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Prenavbar />
      <Navbar />
      <Postnavbar />
      <ContactRibbon />
      <RelevantInfoBanner />
      <Tabs />
      <OfferCards />
      <div className="text-center mt-4 mb-10">
        <h2 className="text-3xl">Potenciá tu conectividad con Personal</h2>
        <p className="opacity-70">
          Encontrá combos de internet, telefonía móvil y TV
        </p>
      </div>
    </>
  );
};

export default Home;
